- group:    Bonus
  start:    22-11-2023 19:30
  deadline: 20-12-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: rio-net
      score: 400
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/blob/master/rio/README.net.md

- group:    Unsafe
  start:    06-12-2023 19:30
  deadline: 20-12-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: arrayvec
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/arrayvec

- group:    Project 3
  start:    29-11-2023 19:30
  deadline: 20-12-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: babencoin
      score: 1
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/babencoin

- group:    Async
  start:    22-11-2023 19:30
  deadline: 06-12-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: rio-multi
      score: 200
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/rio

- group:    Threads & net
  start:    15-11-2023 19:30
  deadline: 29-11-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: pargrep
      score: 200
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/pargrep
    - task: tcp_proxy
      score: 200
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/tcp_proxy

- group:    Project 2
  start:    08-11-2023 19:30
  deadline: 30-11-2023 23:59
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: orm
      score: 1
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/orm

- group:    Macros
  start:    01-11-2023 19:30
  deadline: 15-11-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: stdmacro
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/stdmacro
    - task: gc
      score: 300
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/gc

- group:    Interior mutability & Funcs
  start:    25-10-2023 19:30
  deadline: 09-11-2023 23:59
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: mpsc
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/mpsc
    - task: fswalk
      score: 200
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/fswalk

- group:    Project 1
  start:    18-10-2023 19:30
  deadline: 08-11-2023 23:59
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: chip8
      score: 1
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/chip8

- group:    Generics & Pointers
  start:    11-10-2023 19:30
  deadline: 25-10-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: pstack
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/pstack
    - task: flatmap
      score: 200
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/flatmap

- group:    Traits
  start:    04-10-2023 12:00
  deadline: 18-10-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: trust
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/trust

- group:    Slices & enums
  start:    27-09-2023 19:30
  deadline: 11-10-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: ini
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/ini
    - task: polka
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/polka

- group:    Fun
  start:    20-09-2023 19:30
  deadline: 04-10-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: paperio
      score: 300
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/paperio

- group:    Starters
  start:    13-09-2023 19:30
  deadline: 27-09-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: comm
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/comm
    - task: perc
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/perc

- group:    Test
  start:    01-09-2023 18:00
  deadline: 31-12-2023 23:59
  enabled: true
  tasks:
    - task: add
      score: 0
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/add
