grade:
  image: cr.yandex/crpjkfr9v3se9c5dcf1s/rust/grader
  tags:
    - rust-ysda
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^submit\//'
  script:
    - cd /opt/shad/rust && cargo xtask grade
        --student-repo $CI_PROJECT_DIR
        --original-repo .
        --ci-branch-name $CI_COMMIT_REF_NAME
        --user-id $GITLAB_USER_ID;
  timeout: 10 minutes
