grade:
  image: cr.yandex/crpjkfr9v3se9c5dcf1s/rust/grader
  tags:
    - rust-ysda
  script:
    - if [[ "$CI_COMMIT_REF_NAME" == submit/* ]]; then
        cargo run
        --manifest-path /opt/shad/rust/tools/check/Cargo.toml
        --
        --student-repo $CI_PROJECT_DIR
        --original-repo /opt/shad/rust
        --ci-branch-name $CI_COMMIT_REF_NAME
        --user-id $GITLAB_USER_ID;
      fi
  timeout: 10 minutes
