[workspace]
members = [
    "task/add",
    "task/comm",
    "task/comm/xtask",
    "task/paperio/gui",
    "task/paperio/proto",
    "task/paperio/server",
    "task/paperio/strategy",
    "task/paperio/wasm-launcher",
    "task/paperio/xtask",
    "task/perc",
    "xtask/base",
    "xtask/util",
]
resolver = "2"
