[workspace]
members = [
    "task/add",
    "task/comm",
    "task/comm/xtask",
    "task/flatmap",
    "task/ini",
    "task/paperio/gui",
    "task/paperio/proto",
    "task/paperio/server",
    "task/paperio/strategy",
    "task/paperio/wasm-launcher",
    "task/paperio/xtask",
    "task/perc",
    "task/polka",
    "task/pstack",
    "task/trust",
    "xtask/base",
    "xtask/util",
]
resolver = "2"
