[package]
name = "xtask-base"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
clap = { version = "4.5.17", features = ["derive"] }
git2 = "0.19.0"
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"
xshell = "0.2.6"
xtask-util = { path = "../util" }
