[lint]
fmt = true
clippy = true

[test]
debug = true
release = true

[grade]
allowlist = [
  "src/data.rs",
  "src/error.rs",
  "src/image.rs",
  "src/interpreter.rs",
  "src/managed_interpreter.rs",
  "src/platform.rs",
]
