[lint]
fmt = true
clippy = true

[test]
debug = true
release = true

[grade]
allowlist = [
  "orm-derive/src/lib.rs",
  "src/connection.rs",
  "src/data.rs",
  "src/error.rs",
  "src/lib.rs",
  "src/object.rs",
  "src/storage.rs",
  "src/transaction.rs",
]
