[lint]
fmt = true
clippy = true

[test]
debug = true
release = true

[grade]
allowlist = [
  "src/network.rs",
  "src/network/driver.rs",
  "src/network/udp.rs",
  "src/runtime.rs",
  "src/scheduler.rs",
  "src/scheduler/current_thread.rs",
  "src/scheduler/multi_thread.rs",
]
