[package]
name = "paperio-server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
log = "0.4.22"
paperio-proto = { version = "0.1.0", path = "../proto" }
stderrlog = { git = "https://github.com/CramBL/stderrlog-rs", version = "0.6.0" }
