[package]
name = "xtask-comm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
clap = { version = "4.5.17", features = ["derive"] }
xshell = "0.2.6"
xtask-base = { path = "../../../xtask/base" }
xtask-util = { path = "../../../xtask/util" }
