[package]
name = "comm"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
pretty_assertions = "1.4"
rand = "0.8"
tempfile = "3"

[[bench]]
name = "benches"
harness = false
