[package]
name = "paperio-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.28"
eframe = "0.28"
paperio-proto = { version = "0.1.0", path = "../proto" }
num-traits = "0.2.19"
clap = { version = "4.5.17", features = ["derive"] }
anyhow = "1.0.89"
