[package]
name = "xtask-util"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.87", features = ["std"] }
gix = { version = "0.66.0" }
serde = { version = "1.0.210", features = ["derive"] }
toml = { version = "0.8.19", features = ["parse"] }
